import time

def lyrics_nong_duoi_chan_may():
    # Intro - Nhạc nền
    time.sleep(20)

    # Đoạn 1
    print("Nhớ thương vơi đầy")
    time.sleep(2.5)
    print("Dàn vang lên gió mang theo tâm can đã lâu")
    time.sleep(3)
    print("Không còn thờ ơ, mang tình ta nhiều luyến tiếc")
    time.sleep(2.5)
    print("Bên nhau trọn đời")
    time.sleep(3)
    print("Trời lại không muốn cho, em ra không muốn chơi vơi đâu")
    time.sleep(3)
    print("Cùng tình long lanh có nhưng không thành")
    time.sleep(3)
    print("Tình yêu anh như nắng...")
    time.sleep(2)
    print("Tình yêu anh như nắng...")
    time.sleep(3)

    # Đoạn 2
    print("Tình yêu anh như nắng dời")
    time.sleep(1.5)
    print("Tìm về nhau giữa chân mây")
    time.sleep(1.5)
    print("Dặn lòng không thể lấp đầy")
    time.sleep(1.5)
    print("Em đi vội chẳng giữ lấy")
    time.sleep(1.5)
    print("Phải chi anh là kẻ tới")
    time.sleep(2)
    print("Rời bỏ đi lúc yêu thôi")
    time.sleep(2)
    print("Thì đôi môi đâu thấy")
    time.sleep(2)
    print("Con tim lúc đơn côi")
    time.sleep(2)
    print("Đổi lòng chẳng buông...")
    time.sleep(2)
    print("Chả lại em những nỗi buồn")
    time.sleep(2)
    print("Chả lại những niềm đau")
    time.sleep(2)
    print("Cả những vết thương sâu")
    time.sleep(2)
    print("Thêm bao lâu thì người sẽ thấu")
    time.sleep(2)
    print("Chả lại em những ước nguyện")
    time.sleep(2)
    print("Chả em lúc bình yên")
    time.sleep(2)
    print("Thà giây phút tiếng líu lo")
    time.sleep(3)
    print("Bên hiên đó nắng chiều khẽ rơi...")
    time.sleep(3)
    
    # Đoạn 3 - Replay
    print("Chả lại em những nỗi buồn")
    time.sleep(2)
    print("Chả lại những niềm đau")
    time.sleep(2)
    print("Cả những vết thương sâu")
    time.sleep(2)
    print("Thêm bao lâu thì người sẽ thấu")
    time.sleep(2)
    print("Chả lại em những ước nguyện")
    time.sleep(2)
    print("Chả em lúc bình yên")
    time.sleep(2)
    print("Thà giây phút tiếng líu lo")
    time.sleep(3)
    print("Bên hiên đó nắng chiều khẽ rơi...")
    time.sleep(1)

    # Đoạn cuối
    print("Này thời gian ơi hãy đứng lại")
    time.sleep(2)
    print("Ngày mà ta mới đến nơi")
    time.sleep(2)
    print("Mỉm cười vội chung vẫn")
    time.sleep(3)
    print("Vội vàng trong vô vàn")
    time.sleep(3)
    print("Phải chi anh là kẻ khờ")
    time.sleep(2)
    print("Chờ lại những niềm đau")
    time.sleep(2)
    print("Cả những vết thương sâu")
    time.sleep(2)
    print("Em đừng mong... những điều sẽ tới...")
    time.sleep(4)
    print("Này thời gian ơi hãy đứng lại")
    time.sleep(2)
    print("Ngày mà ta mới đến nơi")
    time.sleep(2)
    print("Mỉm cười vội chung vẫn")
    time.sleep(3)
    print("Vội vàng trong vô vàn")
    time.sleep(3)
    print("Phải chi anh là kẻ khờ")
    time.sleep(2)
    print("Chờ lại những niềm đau")
    time.sleep(2)
    print("Cả những vết thương sâu")
    time.sleep(2)
    print("Em đừng mong... những điều sẽ tới...")

# Chạy chương trình
lyrics_nong_duoi_chan_may()

