import time
import sys

def typewriter_effect(text, speed=0.05):
    """
    Hàm này mô phỏng hiệu ứng đánh máy chữ.
    """
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def lyrics_nong_duoi_chan_may():
    # Intro - Nhạc nền
    time.sleep(20)

    # Đoạn 1
    typewriter_effect("Nhớ thương vơi đầy")
    time.sleep(2.5)
    typewriter_effect("Dàn vang lên gió mang theo tâm can đã lâu")
    time.sleep(3)
    typewriter_effect("Không còn thờ ơ, mang tình ta nhiều luyến tiếc")
    time.sleep(2.5)
    typewriter_effect("Bên nhau trọn đời")
    time.sleep(3)
    typewriter_effect("Trời lại không muốn cho, em ra không muốn chơi vơi đâu")
    time.sleep(3)
    typewriter_effect("Cùng tình long lanh có nhưng không thành")
    time.sleep(3)
    typewriter_effect("Tình yêu anh như nắng...")
    time.sleep(2)
    typewriter_effect("Tình yêu anh như nắng...")
    time.sleep(3)

    # Đoạn 2
    typewriter_effect("Tình yêu anh như nắng dời")
    time.sleep(1.5)
    typewriter_effect("Tìm về nhau giữa chân mây")
    time.sleep(1.5)
    typewriter_effect("Dặn lòng không thể lấp đầy")
    time.sleep(1.5)
    typewriter_effect("Em đi vội chẳng giữ lấy")
    time.sleep(1.5)
    typewriter_effect("Phải chi anh là kẻ tới")
    time.sleep(2)
    typewriter_effect("Rời bỏ đi lúc yêu thôi")
    time.sleep(2)
    typewriter_effect("Thì đôi môi đâu thấy")
    time.sleep(2)
    typewriter_effect("Con tim lúc đơn côi")
    time.sleep(2)
    typewriter_effect("Đổi lòng chẳng buông...")
    time.sleep(2)
    typewriter_effect("Chả lại em những nỗi buồn")
    time.sleep(2)
    typewriter_effect("Chả lại những niềm đau")
    time.sleep(2)
    typewriter_effect("Cả những vết thương sâu")
    time.sleep(2)
    typewriter_effect("Thêm bao lâu thì người sẽ thấu")
    time.sleep(2)
    typewriter_effect("Chả lại em những ước nguyện")
    time.sleep(2)
    typewriter_effect("Chả em lúc bình yên")
    time.sleep(2)
    typewriter_effect("Thà giây phút tiếng líu lo")
    time.sleep(3)
    typewriter_effect("Bên hiên đó nắng chiều khẽ rơi...")
    time.sleep(3)
    
    # Đoạn 3 - Replay
    typewriter_effect("Chả lại em những nỗi buồn")
    time.sleep(2)
    typewriter_effect("Chả lại những niềm đau")
    time.sleep(2)
    typewriter_effect("Cả những vết thương sâu")
    time.sleep(2)
    typewriter_effect("Thêm bao lâu thì người sẽ thấu")
    time.sleep(2)
    typewriter_effect("Chả lại em những ước nguyện")
    time.sleep(2)
    typewriter_effect("Chả em lúc bình yên")
    time.sleep(2)
    typewriter_effect("Thà giây phút tiếng líu lo")
    time.sleep(3)
    typewriter_effect("Bên hiên đó nắng chiều khẽ rơi...")
    time.sleep(1)

    # Đoạn cuối
    typewriter_effect("Này thời gian ơi hãy đứng lại")
    time.sleep(2)
    typewriter_effect("Ngày mà ta mới đến nơi")
    time.sleep(2)
    typewriter_effect("Mỉm cười vội chung vẫn")
    time.sleep(3)
    typewriter_effect("Vội vàng trong vô vàn")
    time.sleep(3)
    typewriter_effect("Phải chi anh là kẻ khờ")
    time.sleep(2)
    typewriter_effect("Chờ lại những niềm đau")
    time.sleep(2)
    typewriter_effect("Cả những vết thương sâu")
    time.sleep(2)
    typewriter_effect("Em đừng mong... những điều sẽ tới...")
    time.sleep(4)
    typewriter_effect("Này thời gian ơi hãy đứng lại")
    time.sleep(2)
    typewriter_effect("Ngày mà ta mới đến nơi")
    time.sleep(2)
    typewriter_effect("Mỉm cười vội chung vẫn")
    time.sleep(3)
    typewriter_effect("Vội vàng trong vô vàn")
    time.sleep(3)
    typewriter_effect("Phải chi anh là kẻ khờ")
    time.sleep(2)
    typewriter_effect("Chờ lại những niềm đau")
    time.sleep(2)
    typewriter_effect("Cả những vết thương sâu")
    time.sleep(2)
    typewriter_effect("Em đừng mong... những điều sẽ tới...")

# Chạy chương trình
lyrics_nong_duoi_chan_may()
